components/video-player.tsx, package.json, pages/v/[id].tsx, yarn.lock
also fix an edge case if a video is deleted but the poster image still loads b/c it is cached for a bit on cdns
=> copy share link to clipboard

components/info-modal.tsx, components/layout.tsx, pages/terms.tsx
- info modal is only for mobile
- change desktop behavior to show open source link and link to mux in bottom nav
- link to an actual /terms page instead of embedding in the invo modal
=> re-work the bottom nav and info modal

pages/assets/[id].tsx
=> Better error messaging for invalid files

components/audio-bars.tsx, components/fullpage-loader.tsx, components/info-modal.tsx, components/layout.tsx, components/record-page.tsx, components/recording-controls.tsx, components/upload-progress-fullpage.tsx, components/video-source-toggle.tsx, pages/index.tsx, pages/v/[id].tsx
Summary:
- using `vw` to make h1s more responsive
- larger loading text
- record page visual tweaks
- lined up tap targets on mobile
- moar hover states
=> sstriegs-typography

pages/terms.tsx
=> Just Work -> JustWork™

.github/workflows/test.yml, components/record-page.spec.js
=> CI setup: use github actions to lint and run tests

components/record-page.tsx
This is my first contribution to this repo. Thank you for the opportunity and I welcome any notes/changes found during review!
=> fix #31 by stopping all tracks in stopRecording()

.eslintignore, components/record-page.tsx, next.config.js, package.json, yarn.lock
Add https://github.com/jagaapple/next-secure-headers/tree/master#rules which sets `X-Frame-Options` among other things.
=> [next.config.js]: More securitah.

components/video-player.tsx, package.json, yarn.lock
- next.js 10
- use plyr so we get speed controls, storyboards, pip, fullscreen easily
closes #37
=> Plyr maybe

components/video-player.tsx
=> better default range color, black on black is not visible

README.md, components/upload-progress-fullpage.tsx, package.json
Bump required version of upchunk and setting a filesize limit of 1GB. Which may be too high?
=> Add an upload filesize limit

README.md, components/video-player.tsx, package.json, yarn.lock
- Updated libraries, Plyr version fixed Firefox player control issue
- Updated README to include permission access settings
- Added playsInline attribute to video for inline video playback
- Set fullscreen.iosNative to open native player on iOS for fullscreen
- Updated styling so that video source is center on mobile
- Increased min-width so controls can be shown
- README updated for styling
=> Fixed Firefox player controls issue plus more

components/video-player.tsx
Set the flag which listens for changes in the tracks
=> Set the captions flag to listen for updates in tracks

.env.test, lib/moderation-action.spec.ts, lib/moderation-action.ts, lib/moderation-google.ts, lib/moderation-hive.spec.ts, lib/moderation-hive.ts, lib/slack-notifier.ts, package.json, pages/api/report.ts, pages/api/webhooks/mux.ts, yarn.lock
Two changes:
If an asset gets a `adult` score of `>= 0.95` then the following will happen:
1. Message posted to slack (see screenshot)
2. Row posted in Airtable in the "Auto Deleted" table
3. The asset's playback ID gets deleted (making the asset un-viewable and un-playable.
This felt like a good middle-ground. We're confident enough in the `adult >= 0.95` benchmark that we can confidently delete that content without anyone ever seeing it. If we get anecdotal reports of content being deleted unexpectedly then we can always go back and add a new playback ID and see if we were too agressive.
Below is the full list of classifications that Hive does. Some of these classifications are the top level ["head" models](https://docs.thehive.ai/reference#classification) -- like `general_nsfw` and …
=> Auto delete bad things & add violent dimension to hive

lib/moderation-utils.spec.ts, lib/moderation-utils.ts
Pass 5 thumbnails to moderation services, rather than 3.
=> Pass more thumbnails to moderation services

lib/moderation-action.spec.ts, lib/moderation-action.ts
Detect and delete any Hive scores for violent content >= 0.85
=> Introduce autodelete for violent content

components/upload-page.tsx, constants.js
Signed-off-by: Jared Smith <jsmith@mux.com>
=> Add UTM links to `mux.com` and `docs.mux.com` from `stream.new`

components/mux-player.tsx, components/mux-video.tsx, components/player-loader.tsx, components/plyr-player.tsx
=> Fix layout for Mux Player

package.json, yarn.lock
Upgrades the player versions to the latest releases 
https://github.com/muxinc/elements/tags
=> Upgrade player versions

package.json, yarn.lock
Another bugfix to fix the captions issue
=> beta 3 for mux-player-react

README.md, components/mux-player.tsx, components/mux-video.tsx, components/player-loader.tsx, components/player-page.tsx, components/plyr-player.tsx, package.json, yarn.lock
=> Update Mux Player to beta.6 and add a color= query param

package.json, yarn.lock
bugfix in this release that fixes currently broken fullscreen behavior
=> bump to mux player beta.12

components/layout.tsx, components/mux-player.tsx, components/player-loader.tsx, components/player-page.tsx, components/report-form.tsx, next.config.js, package.json, pages/v/[id]/embed.tsx, types/index.ts, yarn.lock
functionally, this is working but oh boy do I need help figuring out this typescript
TODO:
✅ use Mux Player for embed view
✅ use latest version of Mux Player
✅ fix CSS on report abuse form being too wide
✅ don't default select "promotes violence" on the report abuse form (too many people were leaving that default, cc: @philcluff )
✅ add twitter player embed functionality
=> Mux Player on embed page, add twitter embed player metadata, update report abuse UI

package.json, yarn.lock
https://github.com/muxinc/elements/releases/tag/%40mux-elements%2Fmux-player%400.1.0-beta.18
=> feat: upgrade Mux elements

components/player-loader.tsx
Activates the Google cast button!
=> feat: add cast sdk script

package.json, yarn.lock
upgrades Mux elements
https://github.com/muxinc/elements/releases
=> fix: upgrade mux-player-react & mux-video-react

components/player-page.tsx
(test this on preview, the behavior on routing readiness is a little different in dev)
=> render loading until the router is ready

components/mux-player.tsx
=> a/b test preferMSE option for Mux Player

components/button.tsx, components/layout.tsx, pages/index.tsx
I think closes #157 
I believe in one of the upgrades of `@mux/mux-uploader` we broke some existing behavior.
Because MuxUploader in pre-1.0 release this was expected while we do some significant refactors. But I think we got a little too aggressive updating without fully QA'ing.
This still needs some cross-device QA before merging.
=> fix action buttons

package.json, yarn.lock
```
"@mux/mux-player-react": "^1.8.0",
"@mux/mux-uploader-react": "^1.0.0-beta.6",
"@mux/mux-video-react": "^0.7.7",
```
=> chore: update elements deps

components/drag-overlay.tsx, package.json, yarn.lock
This fixes display issues in firefox with the drop overlay by specifying absolute position at the app layer
=> fix: Improve drag overlay compat across browsers

components/mux-player.tsx, package.json, yarn.lock
Linter also formatted some unrelated code in the same file.
=> feat: Bump mux-player dep and use the new default theme

components/mux-player.tsx, package.json, yarn.lock
Bumps player dependency which includes a fix for themes not rendering at small sizes.
=> Re-enable new theme
